# .github/workflows/deploy.yml
name: Deploy GitHub Pages
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm install --no-frozen-lockfile

      - run: |
          pnpm --filter ocjs-create-react-app-typescript build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: |
            packages/ocjs-create-react-app-typescript/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
