# .github/workflows/deploy.yml
name: Deploy GitHub Pages
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm install --frozen-lockfile

      - run: |
          pnpm --filter ocjs-create-react-app-typescript build
          pnpm --filter opencascade.js-examples build
          pnpm --filter read-step-calc-aabb build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: |
            packages/ocjs-create-react-app-typescript/build
            packages/opencascade.js-examples/dist
            packages/read-step-calc-aabb/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
